FROM java:8
VOLUME /tmp
ADD build/lib/fileuploadservice-0.1.0.jar fileuploadservice.jar
ADD build/lib/common-0.1.0.jar common.jar
EXPOSE 8080
RUN bash -c 'touch /fileuploadservice.jar'
RUN bash -c 'touch /common.jar'
ENTRYPOINT ["java","-jar","/fileuploadservice.jar"]
